vector_databases:
  faiss:
    use_gpu: false
  milvus:
    host: "localhost"
    port: 19530
    collection_name: "auto_generated"
    dimension: "auto_generated"
  pinecone:
    #api_key: "auto_generated"
    environment: "auto_generated"
    index_name: "auto_generated"
  qdrant:
    mode: "local"  # or "cloud"
    host: "localhost"
    port: 6333
    collection_name: "auto_generated"
    dimension: "auto_generated"
  weaviate:
    mode: "local"  # or "cloud"
    host: "http://localhost:8080"
    class_name: "auto_generated"
    dimension: "auto_generated"

